### ISSUE TITLE
how to get the weight file.txt? (如何获得重量file.txt)

### ISSUE THREAD

**Issue by enviz** [w-zm/python-sentence2vec#1]
please help me out. I am pretty novice at natural language processing.

(请帮帮我。我是自然语言处理方面的新手。)

**Comment by juaner09** [comment]
> please help me out. I am pretty novice at natural language processing.
> 
> (请帮帮我。我是自然语言处理方面的新手。)

找一个通用的数据集，分词统计一下每个词的词频就可以。

**Comment by w-zm** [comment]
> please help me out. I am pretty novice at natural language processing.
> 
> (请帮帮我。我是自然语言处理方面的新手。)

您好，目前代码是直接根据提供的句子语料库进行生成，当然也可以像 @juaner09 说的那样自行进行修改使用通用数据集计算词频。
