### ISSUE TITLE
请问，这个weight_file = './data/weight_file.txt'   # 权重存储路径 的数据格式啥样的

### ISSUE THREAD

**Issue by DiWang4data** [w-zm/python-sentence2vec#2]
您好，请问'./data/weight_file.txt'的数据格式是啥样的

**Comment by w-zm** [comment]
您好，目前的格式是，每行有词与该词的频次组成：词+空格+频次，例：

> word 10

在代码中有体现，暂时是直接统计要使用的句子语料库，见sentence2vec/_sif.py下的generate weight_file函数。
